# learning python - numpy

Jonas Prado - GitHub: joonaspp

In [2]:
#Instalando a biblioteca
#!pip install numpy

In [5]:
#Importando biblioteca
import numpy as np

In [31]:
#Criando array unidimensional
my_array_uni = np.array([1, 2, 3, 4, 5])
my_array_uni_2 = np.arange(5)
print(my_array_uni)
print(my_array_uni_2)

[1 2 3 4 5]
[0 1 2 3 4]


In [32]:
#Criando array bidimensional
my_array_bid = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]) 
print(my_array_bid)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [33]:
#Dimensões do array (linha,coluna)
np.shape(my_array_uni) # (5,)
np.shape(my_array_bid) # (2,5)

(2, 5)

In [34]:
#Redimensionar um array
my_array_red = np.arange(6).reshape((3, 2))
print(my_array_red)

[[0 1]
 [2 3]
 [4 5]]


In [41]:
#Imprimindo os elementos do array individualmente
print(my_array_uni[1]) 
print(my_array_bid[0,4])

2
5


In [42]:
#Modificando elementos do array
my_array_uni[0] = -1 
my_array_bid[0,0] = -1 
print(my_array_uni)
print(my_array_bid) 

[-1  2  3  4  5]
[[-1  2  3  4  5]
 [ 1  2  3  4  5]]
