# learning python - numpy

Jonas Prado - GitHub: joonaspp

In [2]:
#Instalando a biblioteca
#!pip install numpy

In [5]:
#Importando biblioteca
import numpy as np

In [31]:
#Criando array unidimensional
my_array_uni = np.array([1, 2, 3, 4, 5])
my_array_uni_2 = np.arange(5)
print(my_array_uni)
print(my_array_uni_2)

[1 2 3 4 5]
[0 1 2 3 4]


In [32]:
#Criando array bidimensional
my_array_bid = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]) 
print(my_array_bid)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [33]:
#Dimensões do array (linha,coluna)
np.shape(my_array_uni) # (5,)
np.shape(my_array_bid) # (2,5)

(2, 5)

In [34]:
#Redimensionar um array
my_array_red = np.arange(6).reshape((3, 2))
print(my_array_red)

[[0 1]
 [2 3]
 [4 5]]


In [166]:
#Imprimindo os elementos do array individualmente
print(my_array_uni[1]) 
print(my_array_uni[1:3])
print(my_array_uni[1:])
print(my_array_bid[0,4])

2
[2 3]
[2 3 4 5]
5


In [44]:
#Modificando elementos do array
my_array_uni[0] = -1 
my_array_bid[0,0] = -1 
print(my_array_uni)
print(my_array_bid) 

[-1  2  3  4  5]
[[-1  2  3  4  5]
 [ 1  2  3  4  5]]


In [54]:
#Criando array vazia e especificando os tipos de dados
my_array_vaz = np.empty([3,2], dtype = int) # shape, datatype
print(my_array_vaz)

[[7602288 4325421]
 [     82       0]
 [      0       0]]


In [170]:
#Definindo valores de um array unidimensional (zeros, ones, random, random com faixa)
my_array_zer = np.zeros((5)) 
my_array_one = np.ones((5)) 
my_array_rand = np.random.random((5)) 
my_array_rand_fx = np.floor(-11*np.random.random((5))+11) # 0 e 10 
print(my_array_zer)
print(my_array_one)
print(my_array_rand)
print(my_array_rand_fx)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0.66023648 0.31077589 0.75441735 0.72524475 0.9909572 ]
[10.  6.  9.  5.  1.]


In [171]:
#Definindo valores de um array bidimensional (zeros, ones, random, random com faixa)
my_array_bid_zer = np.zeros((2,5)) 
my_array_bid_one = np.ones((2,5)) 
my_array_bid_rand = np.random.random((2,5)) 
my_array_bid_rand_fx = np.floor(-11*np.random.random((2,5))+11) # 0 e 10 
print(my_array_bid_zer)
print(my_array_bid_one)
print(my_array_bid_rand)
print(my_array_bid_rand_fx)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0.36718708 0.73030575 0.9212699  0.47923496 0.07933334]
 [0.8550043  0.08503469 0.96798396 0.24511005 0.1992911 ]]
[[ 9.  5.  5.  2. 10.]
 [ 4.  4.  4.  6.  0.]]


In [174]:
#Extrair linhas ou colunas de um array existente
my_array_ext = np.array([[4, 5], [6, 1]])
my_array_ext_2 = my_array_ext[:, 1]
print(my_array_ext)
print(my_array_ext_2)

[[4 5]
 [6 1]]
[5 1]


In [189]:
#Soma, subtração, multiplicação e divisão dos elementos dos arrays
my_array_a = np.array([[1.0, 2.0], [3.0, 4.0]])
my_array_b = np.array([[5.0, 6.0], [7.0, 8.0]])
print(my_array_a + my_array_b) # Soma
print(my_array_a - my_array_b) # Subtração
print(my_array_a * my_array_b) # Multiplicação
print(my_array_a / my_array_b) # Divisão

[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [191]:
#Multiplicação de matrizes
my_array_a.dot(my_array_b) # [1l x 1c, 1l x 2c] [2l x 1c, 2l x 2c]

array([[19., 22.],
       [43., 50.]])